# Page settings

baseurl = "https://ernest.guevarra.io/cv"
languageCode = "en-gb"
publishDir = "docs"
title = "Ernest Guevarra Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

# Meta
    description = ""
    author = ""

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-3.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ernest Guevarra"
        tagline = "Public Health Specialist, Spatial Epidemiologist, R Developer"
        avatar = "guevarra.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:ernest@guevarra.io"
        title = "ernest@guevarra.io"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-skype"
        url = "skype:ernestguevarra?call"
        title = "ernestguevarra"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//guevarra.io"
        title = "guevarra.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/ernestguevarra"
        title = "linkedin.com/in/ernestguevarra"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/ernestguevarra"
        title = "github.com/ernestguevarra"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/ernestguevarra"
        title = "@ernestguevarra"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Master of Public Health"
        college = "Harvard School of Public Health"
        dates = "2004 - 2005"

        [[params.education.list]]
        degree = "Doctor of Medicine"
        college = "University of the Philippines"
        dates = "1994 - 2001"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "Filipino"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Travel"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Basketball"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "2015 - Present"
        company = "Startup Hubs, San Francisco"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "2014 - 2015"
        company = "Google, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "washdata"
        url = "https://github.com/validmeasures/washdata"
        tagline = "Urban Water and Sanitation Survey Dataset"

        [[params.projects.list]]
        title = "ppitables"
        url = "https://github.com/validmeasures/ppitables"
        tagline = "Lookup tables to generate poverty likelihoods and rates using the Poverty Probability Index (PPI) from country-specific indicators collected from cross-sectional surveys."

        [[params.projects.list]]
        title = "bbw"
        url = "https://github.com/validmeasures/bbw"
        tagline = "The blocked weighted bootstrap (BBW) is an estimation technique for use with data from two-stage cluster sampled surveys in which either prior weighting (e.g. population-proportional sampling or PPS as used in Standardized Monitoring and Assessment of Relief and Transitions or SMART surveys)."

        [[params.projects.list]]
        title = "zscorer"
        url = "https://github.com/nutriverse/zscorer"
        tagline = "Weight-for-age, height-for-age, weight-for-height, BMI-for-age, head circumference-for-age, arm circumference-for-age, subscapular skinfold-for-age and triceps skinfold-for-age z-score calculator"

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Ernest Guevarra"
